image: maven:maven:3.5.2-jdk-8

stages:
  - build
  - test
  - coverage_report

build:
  stage: build
  script:
    - mvn clean package

test:
  stage: test
  script:
    - mvn test

coverage_report:
  stage: coverage_report
  script:
    - mvn jacoco:report
  artifacts:
    reports:
      cobertura: target/site/cobertura/coverage.xml